### ISSUE TITLE
wchar_t

### ISSUE THREAD

**Issue by klemens-morgenstern** [JeffGarland/liaw2019-process#12]
A bit ignored, but important: windows uses wchar_t for most things. This should be supported; I think going for generic string types in the paper to have clear conversion rules is the way to go. 

I think we can add this later, so that for not `std::string` is fine. Just something to remember.

**Comment by JeffGarland** [comment]
So if I'm not mistaken much of this is now resolved?

**Comment by klemens-morgenstern** [comment]
Yes, I just opted for using fs::path on named pipes and have it hidden for environment. Should ndo the trick.
