### ISSUE TITLE
enhanced system -- should we remove?

### ISSUE THREAD

**Issue by JeffGarland** [JeffGarland/liaw2019-process#18]
So this is an issue we discussed some in Aspen.  I don't think we reached consensus on what to do about it.  I'm seeing issues in the paper that Elias is taking but maybe that's due to not seeing that this is a new form?  

Anyway my inclination is to add to open issues/help needed or remove altogether.  Objections?

// EK: Change signature; system takes a string, not an argument pack
template<class... Args>
int system(Args&&... args)
{
  // EK: Change constructor call to taking a path, arguments and something similar to s
  // EK: also, a rogue comma at the end
  process c(forward<Args>(args)...,);
  if (!c.valid())
    return -1;
  c.wait();
  return c.exit_code();
}

**Comment by klemens-morgenstern** [comment]
I think we should remove it and maybe even deprecate ‘std::system‘

**Comment by JeffGarland** [comment]
done.  Changes pushed. I added a process_cuts.org file so we still have the text around in case we want it back.
