### ISSUE TITLE
LEWGI Cologne: add survey of other C++ process libs

### ISSUE THREAD

**Issue by JeffGarland** [JeffGarland/liaw2019-process#29]
Folly was brought up.  I've also used the old school ACE::process in the past.

**Comment by klemens-morgenstern** [comment]
There [`QProcess`](https://doc.qt.io/qt-5/qprocess.html), [`glibmm::spawn`](https://developer.gnome.org/glibmm/stable/group__Spawn.html),
[`cpp-subprocess`](https://github.com/arun11299/cpp-subprocess) and [`reproc`](https://github.com/DaanDeMeyer/reproc), too. 

The `cpp-subprocess` is only available on posix (or was back then) and is the closest to what I wanted to achieve with `boost.process`.

**Comment by JeffGarland** [comment]
Thanks for the list -- I've incorporated these into the paper.
