### ISSUE TITLE
LEWGI Cologne: Why isn't is_open const?

### ISSUE THREAD

**Issue by JeffGarland** [JeffGarland/liaw2019-process#32]
I believe the answer here is that the process can complete during the is_open check and hence the process object needs to be updated.

@klemens-morgenstern can you confirm?

**Comment by klemens-morgenstern** [comment]
Yes, BUT we wouldn't need that to be the case, since we could have the `_exit_code` member (that can be changed) be `mutable`.

**Comment by JeffGarland** [comment]
Yep, but it's sorta a facade because that makes people think its thread safe.  I"m not going to add it to the paper, but just want to to make sure I understood why it's that way currently.
