### ISSUE TITLE
LEWGI Cologne: Why don't write and read take a span?

### ISSUE THREAD

**Issue by JeffGarland** [JeffGarland/liaw2019-process#33]
Elias has already solved this one in his push.  read/write now take span<byte>.  I'm adding the issue so I have a track of the LEWGI issues and their resolutions.

**Comment by JeffGarland** [comment]
@eliaskosunen I notice that your change did add some 'uncertainty' to the comments in the proposal like -- we should clarify that...

```
 // MutableBuffer?
  // ConstBuffer?
```

**Comment by eliaskosunen** [comment]
Yeah, those are concepts from the Networking TS. I'd say those comments can be removed now, though, as it seems like they'll be removed from the TS as well (from what I've heard).

**Comment by JeffGarland** [comment]
right -- I see we have this elsewhere too -- which could be an issue...

```
    // Read some data from the handle.
    // See the Networking TS for more details.
    template<class MutableBufferSequence>
    size_t read_some(const MutableBufferSequence& buffers);

```
