### ISSUE TITLE
Cologne: SG1 question - does terminate on a process block?

### ISSUE THREAD

**Issue by JeffGarland** [JeffGarland/liaw2019-process#44]
This one is for @klemens-morgenstern to answer.
 
Mattias G: If you call terminate on a process does it block?
JG: I'm not sure, will get back to you.

**Comment by klemens-morgenstern** [comment]
It does block until the process is terminated. IT does however not give the child process a chance to react, so it definitely termiantes every single time.

**Comment by JeffGarland** [comment]
Ok so it's the equivalent of a kill -9?   Since obviously the normal kill wouldn't be enough to guarantee the child terminates.

**Comment by klemens-morgenstern** [comment]
Yes, it is kill -9 on linux. A friendly kill request doesn't exist (at least in a reliable way) on windows.

**Comment by JeffGarland** [comment]
Interesting - I didn't realize that.  Thanks.
